//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 07:14:29 PM EEST 
//


package com.ace.ucv.model.xml.student;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for studentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="studentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nume">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="dinkar"/>
 *               &lt;enumeration value="Vaneet"/>
 *               &lt;enumeration value="jasvir"/>
 *               &lt;enumeration value="Draghici"/>
 *               &lt;enumeration value="Paleta"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Prenume">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="kad"/>
 *               &lt;enumeration value="Gupta"/>
 *               &lt;enumeration value="singn"/>
 *               &lt;enumeration value="Andreea"/>
 *               &lt;enumeration value="Petrom"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Telefon">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0374826495"/>
 *               &lt;enumeration value="0375628585"/>
 *               &lt;enumeration value="0735491645"/>
 *               &lt;enumeration value="07355555551"/>
 *               &lt;enumeration value="073222223"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Sex">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Male"/>
 *               &lt;enumeration value="Female"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "studentType", propOrder = {
    "nume",
    "prenume",
    "telefon",
    "sex"
})
public class StudentType {

    @XmlElement(name = "Nume", required = true)
    protected String nume;
    @XmlElement(name = "Prenume", required = true)
    protected String prenume;
    @XmlElement(name = "Telefon", required = true)
    protected String telefon;
    @XmlElement(name = "Sex", required = true)
    protected String sex;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the nume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNume() {
        return nume;
    }

    /**
     * Sets the value of the nume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNume(String value) {
        this.nume = value;
    }

    /**
     * Gets the value of the prenume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrenume() {
        return prenume;
    }

    /**
     * Sets the value of the prenume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrenume(String value) {
        this.prenume = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefon(String value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the sex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
