//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 07:11:14 PM EEST 
//


package com.ace.ucv.model.xml.materie;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for materiaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="materiaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="denumire">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Romana"/>
 *               &lt;enumeration value="Engleza"/>
 *               &lt;enumeration value="Matematica"/>
 *               &lt;enumeration value="Informatica"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="profesor">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Profesor1"/>
 *               &lt;enumeration value="Profesor2"/>
 *               &lt;enumeration value="Profesor3"/>
 *               &lt;enumeration value="Profesor4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="an">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="I"/>
 *               &lt;enumeration value="II"/>
 *               &lt;enumeration value="IV"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="semestru">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "materiaType", propOrder = {
    "denumire",
    "profesor",
    "an",
    "semestru"
})
public class MateriaType {

    @XmlElement(required = true)
    protected String denumire;
    @XmlElement(required = true)
    protected String profesor;
    @XmlElement(required = true)
    protected String an;
    @XmlElement(required = true)
    protected String semestru;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the denumire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenumire() {
        return denumire;
    }

    /**
     * Sets the value of the denumire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenumire(String value) {
        this.denumire = value;
    }

    /**
     * Gets the value of the profesor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfesor() {
        return profesor;
    }

    /**
     * Sets the value of the profesor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfesor(String value) {
        this.profesor = value;
    }

    /**
     * Gets the value of the an property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAn() {
        return an;
    }

    /**
     * Sets the value of the an property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAn(String value) {
        this.an = value;
    }

    /**
     * Gets the value of the semestru property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemestru() {
        return semestru;
    }

    /**
     * Sets the value of the semestru property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemestru(String value) {
        this.semestru = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
